name: ia2_bimestre
description: "Um aplicativo Flutter para gerar imagens usando IA."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  path_provider: ^2.1.3
  # Pacote correto para salvar imagens, compatível com as outras dependências
  image_gallery_saver: ^2.0.3 
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  share_plus: ^9.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  # O pacote 'gallery_saver' foi removido para resolver o conflito.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true